### PR TITLE
Modify highlight component behaviour

### PR DESCRIPTION
**Pull request by andysellick**
This option was matching all of our GOV.UK components but also anything starting with `govuk-`, which included all of the GOVUK Frontend classes. This produced a lot of false positives, making some pages on GOV.UK when viewed with this option very cluttered. Also the false positives didn't link anywhere (the option is meant to link to components on GOV.UK).

Before:

Screen Shot 2019-06-07 at 12 08 26

After:

Screen Shot 2019-06-07 at 12 08 37

### CODE REVIEW

**Comment by andysellick** [comment]
Thanks @alex-ju, I've posted it in #govuk-frontenders.

On your other note, it's not highlighted because that page isn't using it. By strange coincidence I've been looking into this only this morning, the component might need a bit of tweaking but it should be possible. I've added it to our backlog - it was previously not a component because that part of the page was a mustache template, but now we're removed mustache we're free to use components wherever we like 🎉 😄

**Comment by alex-ju** [comment]
Thanks for looking into that @andysellick, sounds like a big win for consistency.

**Comment by andysellick** [comment]
Anyone have the permissions to make a new version with this change in?

**Comment by alex-ju** [comment]
@andysellick just published on AMO for Firefox, but I don't manage to do it for Google, requires to be part of govukdevelopers Google group, which I'm not, and $5 to verify your account

**Pull request merged**
