### PR TITLE
Bump to 1.19.0

### PR DESCRIPTION
**Pull request by sihugh**
Added link to view structured data on your current GOV.UK page (https://github.com/alphagov/govuk-browser-extension/pull/133)

### CODE REVIEW

**Comment by ChrisBAshton** [comment]
As this hasn't been merged yet, could you re-run the rake task to include #136? :)

**Comment by sihugh** [comment]
> As this hasn't been merged yet, could you re-run the rake task to include #136? :)

Sure, I'll put it on my list 👍

**Comment by sihugh** [comment]
@ChrisBAshton this is done!  Any chance of a 👍 ?

**Comment by sihugh** [comment]
Thanks!

**Pull request merged**
